[2022-08-14 16:23:49,180] logger_util.py->write_log line:65 [INFO] ------------------------接口请求开始-------------------------
[2022-08-14 16:23:49,180] logger_util.py->write_log line:65 [INFO] 接口名称：批量发放adf
[2022-08-14 16:23:49,180] logger_util.py->write_log line:65 [INFO] 请求头：None
[2022-08-14 16:23:49,180] logger_util.py->write_log line:65 [INFO] 请求路径：/superAdmin/user-manage/upload-adf
[2022-08-14 16:23:49,181] logger_util.py->write_log line:65 [INFO] 接口替换前的请求数据：{'async': 1}
[2022-08-14 16:23:49,639] logger_util.py->write_log line:65 [INFO] ---------接口返回结果：{"return_code":"SUCCESS","return_msg":{"taskId":80,"checkErrNum":0}}
[2022-08-14 16:23:49,641] logger_util.py->write_log line:65 [INFO] ------------------默认返回的响应结果是字典，调用result_validate方法断言-------------------
[2022-08-14 16:23:49,641] logger_util.py->write_log line:65 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-08-14 16:23:49,641] logger_util.py->write_log line:65 [INFO] 实际结果：{'return_code': 'SUCCESS', 'return_msg': {'taskId': 80, 'checkErrNum': 0}}
[2022-08-14 16:23:49,641] logger_util.py->write_log line:65 [INFO] 接口执行成功
[2022-08-14 16:23:49,641] logger_util.py->write_log line:65 [INFO] ------------------------接口请求结束-------------------------

[2022-08-14 16:23:49,641] logger_util.py->write_log line:65 [INFO] analysic_extract进入正则提取判断
[2022-08-14 16:23:49,642] logger_util.py->write_error_log line:69 [INFO] 分析yaml文件出错,异常信息：Traceback (most recent call last):
  File "C:\Users\pc\Desktop\aiduifen\common\requests_util.py", line 142, in analysis_yaml
    self.analysic_extract(testcase_info, res)
  File "C:\Users\pc\Desktop\aiduifen\common\requests_util.py", line 40, in analysic_extract
    obj = re.search(value, text_result).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

