[2022-08-14 16:31:28,707] logger_util.py->write_log line:65 [INFO] ------------------------接口请求开始-------------------------
[2022-08-14 16:31:28,708] logger_util.py->write_log line:65 [INFO] 接口名称：批量发放adf
[2022-08-14 16:31:28,708] logger_util.py->write_log line:65 [INFO] 请求头：None
[2022-08-14 16:31:28,708] logger_util.py->write_log line:65 [INFO] 请求路径：/superAdmin/user-manage/upload-adf
[2022-08-14 16:31:28,708] logger_util.py->write_log line:65 [INFO] 接口替换前的请求数据：{'async': 1}
[2022-08-14 16:31:29,205] logger_util.py->write_log line:65 [INFO] ---------接口返回结果：{"return_code":"SUCCESS","return_msg":{"taskId":83,"checkErrNum":0}}
[2022-08-14 16:31:29,206] logger_util.py->write_log line:65 [INFO] ------------------默认返回的响应结果是字典，调用result_validate方法断言-------------------
[2022-08-14 16:31:29,206] logger_util.py->write_log line:65 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2022-08-14 16:31:29,207] logger_util.py->write_log line:65 [INFO] 实际结果：{'return_code': 'SUCCESS', 'return_msg': {'taskId': 83, 'checkErrNum': 0}}
[2022-08-14 16:31:29,207] logger_util.py->write_log line:65 [INFO] 接口执行成功
[2022-08-14 16:31:29,207] logger_util.py->write_log line:65 [INFO] ------------------------接口请求结束-------------------------

[2022-08-14 16:31:29,207] logger_util.py->write_log line:65 [INFO] analysic_extract进入正则提取判断
[2022-08-14 16:31:29,208] logger_util.py->write_error_log line:69 [INFO] 分析yaml文件出错,异常信息：Traceback (most recent call last):
  File "C:\Users\pc\Desktop\aiduifen\common\requests_util.py", line 146, in analysis_yaml
    self.analysic_extract(testcase_info, res)
  File "C:\Users\pc\Desktop\aiduifen\common\requests_util.py", line 43, in analysic_extract
    write_log("--------------提取到的值是：%s" %extract_data.group(1))
AttributeError: 'NoneType' object has no attribute 'group'

